### PR TITLE
Fix ERC20 Votes - Broken link in 'Read More'

### LINKED ISSUE #473: Cairo: ERC20 Votes - Broken link in "Read More"
Cairo ERC20 Votes - Read More links to https://docs.openzeppelin.com/contracts-cairo/governance#votes which does not exist.

### PR DESCRIPTION
**Pull request by YanVictorSN**
Close #473

### CODE REVIEW

File: packages/ui/src/cairo/ERC20Controls.svelte [hunk 1]
```diff
@@ -86,7 +86,7 @@
       <span class="ml-1">
         <input type="checkbox" bind:checked={opts.votes}>
       </span>
-      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/governance#votes">
+      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/api/governance#votes">
```
Comment (ericglau) [inline packages/ui/src/cairo/ERC20Controls.svelte:89]:
```suggestion
      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/governance/votes">
```

File: packages/ui/src/cairo/ERC721Controls.svelte [hunk 2]
```diff
@@ -88,7 +88,7 @@
       <span class="ml-1">
         <input type="checkbox" bind:checked={opts.votes}>
       </span>
-      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/governance#votes">
+      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/api/governance#votes">
```
Comment (ericglau) [inline packages/ui/src/cairo/ERC721Controls.svelte:91]:
```suggestion
      <HelpTooltip align="right" link="https://docs.openzeppelin.com/contracts-cairo/governance/votes">
```

**Review by ericglau — COMMENTED** [review]
Thanks for the PR! Just suggested a few changes -- I think it should point to the module documentation rather than the API specification to provide more context for the user.

**Comment by YanVictorSN** [comment]
> Thanks for the PR! Just suggested a few changes -- I think it should point to the module documentation rather than the API specification to provide more context for the user.

@ericglau Thank you! I just committed the suggested changes.

**Review by ericglau — APPROVED** [review]
